(() => {
  const photos = {
    'drywall-plaster.html': [['https://images.pexels.com/photos/5691622/pexels-photo-5691622.jpeg?auto=compress&cs=tinysrgb&w=1200','Drywall finishing and surface preparation'],['https://images.pexels.com/photos/7218525/pexels-photo-7218525.jpeg?auto=compress&cs=tinysrgb&w=1200','Interior wall painting tools and freshly painted wall']],
    'fences-awnings.html': [['https://images.pexels.com/photos/145685/pexels-photo-145685.jpeg?auto=compress&cs=tinysrgb&w=1200','Landscaped property boundary and garden'],['https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1200','Residential property with a finished yard']],
    'pavers-asphalt.html': [['https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1200','Finished residential driveway and front approach'],['https://images.pexels.com/photos/145685/pexels-photo-145685.jpeg?auto=compress&cs=tinysrgb&w=1200','Garden path and landscaped outdoor area']],
    'property-lines-sprinklers.html': [['https://images.pexels.com/photos/145685/pexels-photo-145685.jpeg?auto=compress&cs=tinysrgb&w=1200','Healthy landscaped yard with established plantings'],['https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1200','Residential lawn and property exterior']],
    'carpet-vinyl.html': [['https://images.pexels.com/photos/1571458/pexels-photo-1571458.jpeg?auto=compress&cs=tinysrgb&w=1200','Finished residential room with clean flooring'],['https://images.pexels.com/photos/276528/pexels-photo-276528.jpeg?auto=compress&cs=tinysrgb&w=1200','Finished interior living space and flooring']],
    'house-moving.html': [['https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1200','Residential home and site access'],['https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1200','Residential house exterior']],
    'services.html': [['https://images.pexels.com/photos/7218525/pexels-photo-7218525.jpeg?auto=compress&cs=tinysrgb&w=1200','Interior painting and wall finishing'],['https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1200','Landscaped residential property and driveway']]
  };
  const page=location.pathname.split('/').pop()||'index.html',pair=photos[page];
  if(!pair||document.querySelector('[data-stock-photo-pair]'))return;
  const main=document.querySelector('main');if(!main)return;
  const style=document.createElement('style');style.textContent='.stock-photo-pair{display:grid;grid-template-columns:1fr 1fr;gap:18px;width:min(1120px,calc(100% - 40px));margin:0 auto;padding:64px 0}.stock-photo-pair figure{margin:0;min-height:340px;overflow:hidden;border-radius:8px;background:#0d131a}.stock-photo-pair img{display:block;width:100%;height:100%;min-height:340px;object-fit:cover}@media(max-width:720px){.stock-photo-pair{grid-template-columns:1fr;padding:44px 0}.stock-photo-pair figure,.stock-photo-pair img{min-height:260px}}';document.head.appendChild(style);
  const section=document.createElement('section');section.className='stock-photo-pair';section.dataset.stockPhotoPair='true';section.setAttribute('aria-label','Project inspiration');pair.forEach(([src,alt])=>{const figure=document.createElement('figure'),img=document.createElement('img');img.src=src;img.alt=alt;img.loading='lazy';figure.appendChild(img);section.appendChild(figure)});const cta=main.querySelector('.cta');main.insertBefore(section,cta||null);
})();
